document.getElementById("myimage").src= "https://www.holidify.com/blog/wp-content/uploads/2013/11/Bhangarh-Fort.jpg"
document.getElementById("content").innerHTML="The ghost town of Bhangarh is one of the scariest, spookiest places you could possibly imagine, not to mention, one of the most haunted places in India. Situated near a popular forest, this town is now slowly luring visitors from around the area, and country, for all the wrong reasons.It should be noted that if you decide to visit this place after the sun has gone down, you won’t be allowed to. In fact, there is a strict warning about how dangerous this place becomes after sunset.The story which this town is well-known for tells the tale of a magician who fell in love with the local princess of the area even though their match was impossible. Being quite the master of dark magic, he decided to cast a spell on her to make her surrender to him. However, the princess learned of his plans and found a way to kill him. Before his death, however, the magician cast a dark spell on the palace which caused its doom.Despite Bhangarh Fort being regarded as one of the most horror haunted places in India has been officially promoted as a tourist destination. However, once the night falls and the darkness takes over, this place becomes deserted, leaving it prey to the supposed ‘supernatural’. The mystery of Bhangarh Fort also featured on a TV show and you can have a look at the most haunted place in India’s video yourself."
function myfunction2()
{
	document.getElementById("myimage").src= "https://www.holidify.com/blog/wp-content/uploads/2013/11/Kuldhara.jpg"
	document.getElementById("heading").innerHTML= "2.Kuldhara Rajasthan"
	document.getElementById("content").innerHTML="The village of Kuldhara is popularly known to be a deserted ghost village that has been abandoned since 1800s. It is said to carry a curse of the villagers who vanished from there overnight, after having lived there for over 7 centuries.The village lies in ruins, established in 1291 by the Paliwal Brahmins, who were a very prosperous clan and were known for their business acumen and agricultural knowledge. It has been said that one night in 1825 all the people in Kuldhara and nearby 83 villages vanished in dark. All of a sudden and without any warning.Tales about this mystery include the fact that Salim Singh, the minister of the state, once visited this village and fell in love with the beautiful daughter of chieftain wanting to marry her. The minister threatened the villagers by saying that if they did not marry the girl to him, he would levy huge taxes. The chief of the village along with those of adjoining villages decided to abandon and migrate elsewhere to protect the girl’s honour. Nobody saw them leave nor did anyone figure where they went, they simply vanished. It is said that the villagers also cast a spell on the village as they left, cursing anyone who tried to inhabit the land."
}
function myfunction3()
{
	document.getElementById("myimage").src= "https://www.holidify.com/blog/wp-content/uploads/2013/11/Vrindavan-Society.jpg"
	document.getElementById("heading").innerHTML= "3. D’Souza Chawl in Mahim – Mumbai"
	document.getElementById("content").innerHTML="Owing to D’Souza Chawl, Mahim has acquired the status of being the most haunted place in Mumbai. It is said that a woman fell into the water and died crying for help in the well. Probably that is why most people say that they’ve witnessed a woman lurking around the well and the nearby area."
}
function myfunction4()
{
	document.getElementById("myimage").src= "https://1.bp.blogspot.com/-a_JHLIzCyq8/TxQZDBEya9I/AAAAAAAAAqE/3takPo2vp6c/s1600/draft_lens17619353module148111049photo_1300041759Brij_Raj_Bhavan_Palace_in.jpg"
	document.getElementById("heading").innerHTML= "4. The Shaniwarwada Fort – Pune"
	document.getElementById("content").innerHTML="Known for its sheer architectural brilliance, this fort has witnessed various spooky occurrences. It is believed that the level of supernatural activity is on its zenith on every full moon night. The mysterious story behind the strange activities suggests that a young prince was brutally murdered here which is maybe why his spirit haunts the place and when the night falls, sounds of him shrieking can be heard. There are many locals who actually camp at night on the fort grounds just to hear the little boy’s scream.It is preferable to visit the fort during day hours since the fort is deserted at night except for maybe a caretaker. Visit this place at your own risk as this would definitely be the scariest haunted place in Pune, India."
}
function myfunction5()
{
	document.getElementById("myimage").src= "https://www.holidify.com/blog/wp-content/uploads/2015/08/Raj-Kiran-Hotel.jpg"
	document.getElementById("heading").innerHTML= " 5. GP Block – Meerut"
	document.getElementById("content").innerHTML="GP Block in Meerut is also very notoriously known for all the paranormal activity it beholds. Despite being a popular zone, there have been reportedly a lot of strange sightings.For instance people who pass this place claim to have seen four males sitting together and enjoying an alcoholic beverage by the light of a single candle. At first, this was not considered spooky for it could just be four friends having a good time but once it was established that it was indeed four ghosts, people in and around the area became increasingly interested. In addition, some claim to also witness a young girl coming out of the house in what many people believe to be a red dress. With time people have abandoned that place for obvious reasons but it continues to catch the fancy of those who love the paranormal."
}
